# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.16

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/nikhil/Documents/bluedroid.for.linux

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/nikhil/Documents/bluedroid.for.linux

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/nikhil/Documents/bluedroid.for.linux/CMakeFiles /home/nikhil/Documents/bluedroid.for.linux/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/nikhil/Documents/bluedroid.for.linux/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named libbt-brcm_bta

# Build rule for target.
libbt-brcm_bta: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 libbt-brcm_bta
.PHONY : libbt-brcm_bta

# fast build rule for target.
libbt-brcm_bta/fast:
	$(MAKE) -f bta/CMakeFiles/libbt-brcm_bta.dir/build.make bta/CMakeFiles/libbt-brcm_bta.dir/build
.PHONY : libbt-brcm_bta/fast

#=============================================================================
# Target rules for targets named libbt-brcm_gki

# Build rule for target.
libbt-brcm_gki: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 libbt-brcm_gki
.PHONY : libbt-brcm_gki

# fast build rule for target.
libbt-brcm_gki/fast:
	$(MAKE) -f gki/CMakeFiles/libbt-brcm_gki.dir/build.make gki/CMakeFiles/libbt-brcm_gki.dir/build
.PHONY : libbt-brcm_gki/fast

#=============================================================================
# Target rules for targets named libbt-hci

# Build rule for target.
libbt-hci: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 libbt-hci
.PHONY : libbt-hci

# fast build rule for target.
libbt-hci/fast:
	$(MAKE) -f hci/CMakeFiles/libbt-hci.dir/build.make hci/CMakeFiles/libbt-hci.dir/build
.PHONY : libbt-hci/fast

#=============================================================================
# Target rules for targets named bluetooth.default

# Build rule for target.
bluetooth.default: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 bluetooth.default
.PHONY : bluetooth.default

# fast build rule for target.
bluetooth.default/fast:
	$(MAKE) -f main/CMakeFiles/bluetooth.default.dir/build.make main/CMakeFiles/bluetooth.default.dir/build
.PHONY : bluetooth.default/fast

#=============================================================================
# Target rules for targets named libbt-brcm_stack

# Build rule for target.
libbt-brcm_stack: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 libbt-brcm_stack
.PHONY : libbt-brcm_stack

# fast build rule for target.
libbt-brcm_stack/fast:
	$(MAKE) -f stack/CMakeFiles/libbt-brcm_stack.dir/build.make stack/CMakeFiles/libbt-brcm_stack.dir/build
.PHONY : libbt-brcm_stack/fast

#=============================================================================
# Target rules for targets named libbt-vendor

# Build rule for target.
libbt-vendor: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 libbt-vendor
.PHONY : libbt-vendor

# fast build rule for target.
libbt-vendor/fast:
	$(MAKE) -f devices/rtk8723/libbt/CMakeFiles/libbt-vendor.dir/build.make devices/rtk8723/libbt/CMakeFiles/libbt-vendor.dir/build
.PHONY : libbt-vendor/fast

#=============================================================================
# Target rules for targets named bdt

# Build rule for target.
bdt: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 bdt
.PHONY : bdt

# fast build rule for target.
bdt/fast:
	$(MAKE) -f test/bluedroidtest/CMakeFiles/bdt.dir/build.make test/bluedroidtest/CMakeFiles/bdt.dir/build
.PHONY : bdt/fast

#=============================================================================
# Target rules for targets named libbt-utils

# Build rule for target.
libbt-utils: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 libbt-utils
.PHONY : libbt-utils

# fast build rule for target.
libbt-utils/fast:
	$(MAKE) -f utils/CMakeFiles/libbt-utils.dir/build.make utils/CMakeFiles/libbt-utils.dir/build
.PHONY : libbt-utils/fast

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... edit_cache"
	@echo "... libbt-brcm_bta"
	@echo "... libbt-brcm_gki"
	@echo "... libbt-hci"
	@echo "... bluetooth.default"
	@echo "... libbt-brcm_stack"
	@echo "... libbt-vendor"
	@echo "... bdt"
	@echo "... libbt-utils"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

